// The example sites. Each one has a folder, examples/<id>/, holding its page in
// index.html and its tests in tests.yaml. Order matters: sites group by category
// in this order, and the ports below run from 3001 upwards in the same order.
// Each category is one theme, named in one word for a kind of app a person would
// recognise, and every site in it shares that theme's accent.
export const SITES = {
  "address-form": { name: "Address form", category: "Shopping", host: "localhost:3001", accent: "#b45309" },
  "coupon-code": { name: "Coupon code", category: "Shopping", host: "localhost:3002", accent: "#b45309" },
  "pricing-tabs": { name: "Pricing tabs", category: "Shopping", host: "localhost:3003", accent: "#b45309" },
  "quantity-stepper": { name: "Quantity stepper", category: "Shopping", host: "localhost:3004", accent: "#b45309" },
  "shipping-options": { name: "Shipping options", category: "Shopping", host: "localhost:3005", accent: "#b45309" },
  "shopping-cart": { name: "Shopping cart", category: "Shopping", host: "localhost:3006", accent: "#b45309" },
  "contact-form": { name: "Contact form", category: "Support", host: "localhost:3007", accent: "#0f766e" },
  "faq-accordion": { name: "FAQ accordion", category: "Support", host: "localhost:3008", accent: "#0f766e" },
  "help-center": { name: "Help center", category: "Support", host: "localhost:3009", accent: "#0f766e" },
  "live-chat": { name: "Live chat", category: "Support", host: "localhost:3010", accent: "#0f766e" },
  "status-page": { name: "Status page", category: "Support", host: "localhost:3011", accent: "#0f766e" },
  "ticket-form": { name: "Support ticket", category: "Support", host: "localhost:3012", accent: "#0f766e" },
  "cookie-consent": { name: "Cookie consent", category: "Accounts", host: "localhost:3013", accent: "#1d4ed8" },
  "login": { name: "Login", category: "Accounts", host: "localhost:3014", accent: "#1d4ed8" },
  "password-reset": { name: "Password reset", category: "Accounts", host: "localhost:3015", accent: "#1d4ed8" },
  "password-strength": { name: "Password strength", category: "Accounts", host: "localhost:3016", accent: "#1d4ed8" },
  "profile-settings": { name: "Profile settings", category: "Accounts", host: "localhost:3017", accent: "#1d4ed8" },
  "signup-wizard": { name: "Signup wizard", category: "Accounts", host: "localhost:3018", accent: "#1d4ed8" },
  "theme-settings": { name: "Theme settings", category: "Accounts", host: "localhost:3019", accent: "#1d4ed8" },
  "two-factor": { name: "Two-factor code", category: "Accounts", host: "localhost:3020", accent: "#1d4ed8" },
  "bulk-actions": { name: "Bulk actions", category: "Admin", host: "localhost:3021", accent: "#475569" },
  "confirm-dialog": { name: "Confirm dialog", category: "Admin", host: "localhost:3022", accent: "#475569" },
  "delete-account": { name: "Delete account", category: "Admin", host: "localhost:3023", accent: "#475569" },
  "feature-flags": { name: "Feature flags", category: "Admin", host: "localhost:3024", accent: "#475569" },
  "team-directory": { name: "Sortable table", category: "Admin", host: "localhost:3025", accent: "#475569" },
  "user-roles": { name: "User roles", category: "Admin", host: "localhost:3026", accent: "#475569" },
  "city-search": { name: "City autocomplete", category: "Travel", host: "localhost:3027", accent: "#0e7490" },
  "currency-switcher": { name: "Currency switcher", category: "Travel", host: "localhost:3028", accent: "#0e7490" },
  "flight-search": { name: "Flight search", category: "Travel", host: "localhost:3029", accent: "#0e7490" },
  "seat-picker": { name: "Seat picker", category: "Travel", host: "localhost:3030", accent: "#0e7490" },
  "store-locator": { name: "Store locator", category: "Travel", host: "localhost:3031", accent: "#0e7490" },
  "table-booking": { name: "Table booking", category: "Travel", host: "localhost:3032", accent: "#0e7490" },
  "unit-converter": { name: "Unit converter", category: "Travel", host: "localhost:3033", accent: "#0e7490" },
  "weather-widget": { name: "Weather widget", category: "Travel", host: "localhost:3034", accent: "#0e7490" },
  "expense-splitter": { name: "Expense splitter", category: "Banking", host: "localhost:3035", accent: "#a16207" },
  "loan-calculator": { name: "Loan calculator", category: "Banking", host: "localhost:3036", accent: "#a16207" },
  "money-transfer": { name: "Money transfer", category: "Banking", host: "localhost:3037", accent: "#a16207" },
  "statement-filter": { name: "Statement filter", category: "Banking", host: "localhost:3038", accent: "#a16207" },
  "tip-calculator": { name: "Tip calculator", category: "Banking", host: "localhost:3039", accent: "#a16207" },
  "transaction-search": { name: "Transaction search", category: "Banking", host: "localhost:3040", accent: "#a16207" },
  "paged-list": { name: "Paginated list", category: "Search", host: "localhost:3041", accent: "#0369a1" },
  "product-filters": { name: "Product filters", category: "Search", host: "localhost:3042", accent: "#0369a1" },
  "product-search": { name: "Product search", category: "Search", host: "localhost:3043", accent: "#0369a1" },
  "recent-searches": { name: "Recent searches", category: "Search", host: "localhost:3044", accent: "#0369a1" },
  "search-suggestions": { name: "Search suggestions", category: "Search", host: "localhost:3045", accent: "#0369a1" },
  "sort-results": { name: "Sort results", category: "Search", host: "localhost:3046", accent: "#0369a1" },
  "comment-thread": { name: "Comment thread", category: "Social", host: "localhost:3047", accent: "#be185d" },
  "follow-list": { name: "Follow list", category: "Social", host: "localhost:3048", accent: "#be185d" },
  "like-button": { name: "Like button", category: "Social", host: "localhost:3049", accent: "#be185d" },
  "activity-feed": { name: "Load more feed", category: "Social", host: "localhost:3050", accent: "#be185d" },
  "newsletter-signup": { name: "Newsletter signup", category: "Social", host: "localhost:3051", accent: "#be185d" },
  "post-composer": { name: "Post composer", category: "Social", host: "localhost:3052", accent: "#be185d" },
  "wishlist": { name: "Wishlist", category: "Social", host: "localhost:3053", accent: "#be185d" },
  "bulk-archive": { name: "Bulk archive", category: "Inbox", host: "localhost:3054", accent: "#4338ca" },
  "compose-mail": { name: "Compose mail", category: "Inbox", host: "localhost:3055", accent: "#4338ca" },
  "mail-labels": { name: "Mail labels", category: "Inbox", host: "localhost:3056", accent: "#4338ca" },
  "message-list": { name: "Message list", category: "Inbox", host: "localhost:3057", accent: "#4338ca" },
  "notifications-center": { name: "Notifications", category: "Inbox", host: "localhost:3058", accent: "#4338ca" },
  "unread-filter": { name: "Unread filter", category: "Inbox", host: "localhost:3059", accent: "#4338ca" },
  "autosave-editor": { name: "Autosave draft", category: "Productivity", host: "localhost:3060", accent: "#7c3aed" },
  "checklist-template": { name: "Checklist template", category: "Productivity", host: "localhost:3061", accent: "#7c3aed" },
  "event-scheduler": { name: "Event scheduler", category: "Productivity", host: "localhost:3062", accent: "#7c3aed" },
  "kanban-board": { name: "Kanban board", category: "Productivity", host: "localhost:3063", accent: "#7c3aed" },
  "notes-app": { name: "Notes", category: "Productivity", host: "localhost:3064", accent: "#7c3aed" },
  "todo-list": { name: "To-do list", category: "Productivity", host: "localhost:3065", accent: "#7c3aed" },
  "audio-player": { name: "Audio player", category: "Media", host: "localhost:3066", accent: "#a21caf" },
  "image-carousel": { name: "Image carousel", category: "Media", host: "localhost:3067", accent: "#a21caf" },
  "photo-gallery": { name: "Photo gallery", category: "Media", host: "localhost:3068", accent: "#a21caf" },
  "playlist": { name: "Playlist", category: "Media", host: "localhost:3069", accent: "#a21caf" },
  "video-captions": { name: "Video captions", category: "Media", host: "localhost:3070", accent: "#a21caf" },
  "video-quality": { name: "Video quality", category: "Media", host: "localhost:3071", accent: "#a21caf" },
  "appointment-booking": { name: "Appointment booking", category: "Health", host: "localhost:3072", accent: "#4d7c0f" },
  "bmi-calculator": { name: "BMI calculator", category: "Health", host: "localhost:3073", accent: "#4d7c0f" },
  "habit-tracker": { name: "Habit tracker", category: "Health", host: "localhost:3074", accent: "#4d7c0f" },
  "medication-reminders": { name: "Medication reminders", category: "Health", host: "localhost:3075", accent: "#4d7c0f" },
  "symptom-form": { name: "Symptom form", category: "Health", host: "localhost:3076", accent: "#4d7c0f" },
  "water-tracker": { name: "Water tracker", category: "Health", host: "localhost:3077", accent: "#4d7c0f" },
  "chart-legend": { name: "Chart legend", category: "Dashboards", host: "localhost:3078", accent: "#5b21b6" },
  "date-range": { name: "Date range", category: "Dashboards", host: "localhost:3079", accent: "#5b21b6" },
  "empty-dashboard": { name: "Empty dashboard", category: "Dashboards", host: "localhost:3080", accent: "#5b21b6" },
  "kpi-goals": { name: "KPI goals", category: "Dashboards", host: "localhost:3081", accent: "#5b21b6" },
  "metric-tiles": { name: "Metric tiles", category: "Dashboards", host: "localhost:3082", accent: "#5b21b6" },
  "report-builder": { name: "Report builder", category: "Dashboards", host: "localhost:3083", accent: "#5b21b6" },
  "certificate-form": { name: "Certificate form", category: "Learning", host: "localhost:3084", accent: "#78350f" },
  "feedback-rating": { name: "Feedback rating", category: "Learning", host: "localhost:3085", accent: "#78350f" },
  "flashcards": { name: "Flashcards", category: "Learning", host: "localhost:3086", accent: "#78350f" },
  "lesson-progress": { name: "Lesson progress", category: "Learning", host: "localhost:3087", accent: "#78350f" },
  "poll-voting": { name: "Poll", category: "Learning", host: "localhost:3088", accent: "#78350f" },
  "quick-survey": { name: "Quick survey", category: "Learning", host: "localhost:3089", accent: "#78350f" },
  "quiz-app": { name: "Quiz", category: "Learning", host: "localhost:3090", accent: "#78350f" },
  "memory-match": { name: "Memory match", category: "Games", host: "localhost:3091", accent: "#9f1239" },
  "number-guess": { name: "Number guess", category: "Games", host: "localhost:3092", accent: "#9f1239" },
  "rock-paper-scissors": { name: "Rock paper scissors", category: "Games", host: "localhost:3093", accent: "#9f1239" },
  "score-board": { name: "Scoreboard", category: "Games", host: "localhost:3094", accent: "#9f1239" },
  "tic-tac-toe": { name: "Tic tac toe", category: "Games", host: "localhost:3095", accent: "#9f1239" },
  "word-scramble": { name: "Word scramble", category: "Games", host: "localhost:3096", accent: "#9f1239" },
  "click-counter": { name: "Counter", category: "Misc", host: "localhost:3097", accent: "#52525b" },
  "flaky-app": { name: "Flaky app", category: "Misc", host: "localhost:3098", accent: "#52525b", storageKeys: ["flaky-app-waitlist"] },
  "offline-banner": { name: "Offline banner", category: "Misc", host: "localhost:3099", accent: "#52525b" },
  "retry-on-error": { name: "Retry on error", category: "Misc", host: "localhost:3100", accent: "#52525b" },
};

export const SITE_IDS = Object.keys(SITES);
