// The example sites. Each one has a folder, examples/<id>/, holding its page in
// index.html and its tests in tests.yaml. Order matters: sites group by category
// in this order, and the ports below run from 3001 upwards in the same order.
export const SITES = {
  "contact-form": { name: "Contact form", category: "Forms", host: "localhost:3001", accent: "#0f766e" },
  "signup-wizard": { name: "Signup wizard", category: "Forms", host: "localhost:3002", accent: "#0f766e" },
  "newsletter-signup": { name: "Newsletter signup", category: "Forms", host: "localhost:3003", accent: "#0f766e" },
  "password-strength": { name: "Password strength", category: "Forms", host: "localhost:3004", accent: "#0f766e" },
  "feedback-rating": { name: "Feedback rating", category: "Forms", host: "localhost:3005", accent: "#0f766e" },
  "address-form": { name: "Address form", category: "Forms", host: "localhost:3006", accent: "#0f766e" },
  "quick-survey": { name: "Quick survey", category: "Forms", host: "localhost:3007", accent: "#0f766e" },
  "table-booking": { name: "Table booking", category: "Forms", host: "localhost:3008", accent: "#0f766e" },
  "post-composer": { name: "Post composer", category: "Forms", host: "localhost:3009", accent: "#0f766e" },
  "unit-converter": { name: "Unit converter", category: "Forms", host: "localhost:3010", accent: "#0f766e" },
  "login": { name: "Login", category: "Accounts", host: "localhost:3011", accent: "#1d4ed8" },
  "password-reset": { name: "Password reset", category: "Accounts", host: "localhost:3012", accent: "#1d4ed8" },
  "two-factor": { name: "Two-factor code", category: "Accounts", host: "localhost:3013", accent: "#1d4ed8" },
  "profile-settings": { name: "Profile settings", category: "Accounts", host: "localhost:3014", accent: "#1d4ed8" },
  "delete-account": { name: "Delete account", category: "Accounts", host: "localhost:3015", accent: "#1d4ed8" },
  "cookie-consent": { name: "Cookie consent", category: "Accounts", host: "localhost:3016", accent: "#1d4ed8" },
  "shopping-cart": { name: "Shopping cart", category: "Shopping", host: "localhost:3017", accent: "#b45309" },
  "product-filters": { name: "Product filters", category: "Shopping", host: "localhost:3018", accent: "#b45309" },
  "coupon-code": { name: "Coupon code", category: "Shopping", host: "localhost:3019", accent: "#b45309" },
  "shipping-options": { name: "Shipping options", category: "Shopping", host: "localhost:3020", accent: "#b45309" },
  "wishlist": { name: "Wishlist", category: "Shopping", host: "localhost:3021", accent: "#b45309" },
  "product-search": { name: "Product search", category: "Shopping", host: "localhost:3022", accent: "#b45309" },
  "quantity-stepper": { name: "Quantity stepper", category: "Shopping", host: "localhost:3023", accent: "#b45309" },
  "currency-switcher": { name: "Currency switcher", category: "Shopping", host: "localhost:3024", accent: "#b45309" },
  "todo-list": { name: "To-do list", category: "Productivity", host: "localhost:3025", accent: "#7c3aed" },
  "notes-app": { name: "Notes", category: "Productivity", host: "localhost:3026", accent: "#7c3aed" },
  "kanban-board": { name: "Kanban board", category: "Productivity", host: "localhost:3027", accent: "#7c3aed" },
  "habit-tracker": { name: "Habit tracker", category: "Productivity", host: "localhost:3028", accent: "#7c3aed" },
  "event-scheduler": { name: "Event scheduler", category: "Productivity", host: "localhost:3029", accent: "#7c3aed" },
  "expense-splitter": { name: "Expense splitter", category: "Productivity", host: "localhost:3030", accent: "#7c3aed" },
  "pricing-tabs": { name: "Pricing tabs", category: "Navigation & content", host: "localhost:3031", accent: "#be185d" },
  "faq-accordion": { name: "FAQ accordion", category: "Navigation & content", host: "localhost:3032", accent: "#be185d" },
  "confirm-dialog": { name: "Confirm dialog", category: "Navigation & content", host: "localhost:3033", accent: "#be185d" },
  "paged-list": { name: "Paginated list", category: "Navigation & content", host: "localhost:3034", accent: "#be185d" },
  "photo-gallery": { name: "Photo gallery", category: "Navigation & content", host: "localhost:3035", accent: "#be185d" },
  "city-search": { name: "City autocomplete", category: "Navigation & content", host: "localhost:3036", accent: "#be185d" },
  "team-directory": { name: "Sortable table", category: "Navigation & content", host: "localhost:3037", accent: "#be185d" },
  "activity-feed": { name: "Load more feed", category: "Navigation & content", host: "localhost:3038", accent: "#be185d" },
  "help-center": { name: "Help center", category: "Navigation & content", host: "localhost:3039", accent: "#be185d" },
  "theme-settings": { name: "Theme settings", category: "Navigation & content", host: "localhost:3040", accent: "#be185d" },
  "click-counter": { name: "Counter", category: "Calculators & data", host: "localhost:3041", accent: "#0e7490" },
  "tip-calculator": { name: "Tip calculator", category: "Calculators & data", host: "localhost:3042", accent: "#0e7490" },
  "loan-calculator": { name: "Loan calculator", category: "Calculators & data", host: "localhost:3043", accent: "#0e7490" },
  "quiz-app": { name: "Quiz", category: "Calculators & data", host: "localhost:3044", accent: "#0e7490" },
  "poll-voting": { name: "Poll", category: "Calculators & data", host: "localhost:3045", accent: "#0e7490" },
  "weather-widget": { name: "Weather widget", category: "Calculators & data", host: "localhost:3046", accent: "#0e7490" },
  "notifications-center": { name: "Notifications", category: "States & feedback", host: "localhost:3047", accent: "#4d7c0f" },
  "retry-on-error": { name: "Retry on error", category: "States & feedback", host: "localhost:3048", accent: "#4d7c0f" },
  "autosave-editor": { name: "Autosave draft", category: "States & feedback", host: "localhost:3049", accent: "#4d7c0f" },
  "flaky-app": { name: "Flaky app", category: "States & feedback", host: "localhost:3050", accent: "#4d7c0f", storageKeys: ["flaky-app-waitlist"] },
};

export const SITE_IDS = Object.keys(SITES);
